[tool.poetry]
name = "homework-22"
version = "0.1.0"
description = ""
authors = ["Евгения Крюгер <Evgenia.Kryuger@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
